### ISSUE TITLE
Search on Observation using date range and category yields no hits

### ISSUE THREAD

**Issue by Tagertswe** [jmiddleton/cassandra-fhir-index#1] opened 2016-08-12 06:54 UTC
Greetings!
I was interested in your project, and decided to try it out.
I did however modify the search index by accordingly:

CREATE CUSTOM INDEX idx_fhir_resources ON FHIR_RESOURCES (content)
     USING 'io.puntanegra.fhir.index.FhirIndex'
     WITH OPTIONS = {
        'refresh_seconds' : '5',
        'search': '{
            resources : {
               Patient : ["name", "identifier", "family", "email", "active"],
               Observation : ["date", "category"]
            }
        }'
     };

And wanted to search on multiple hits on category and a date range.
Examples tried: (the dashes and colons are of course 'escaped' in the query)
date:[2016-08-11T16:16:23 TO 2016-08-11T16:16:24] 
date:2016-08-11T16:16:23

I was just wondering if date is implemented?
You do suggest it is, in the example documentation, but I've not been able to search internally in the json column on the effectiveDateTime column using date.

This query is working great:

String test = "SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation" +
//                " OR category:MDC\_PULS\_OXIM\_SAT\_O2 OR category:MDC\_PULS\_OXIM\_PULS\_RATE')" +
//                ""+"  LIMIT 50;";
ResultSet rt = session.execute(test);

I would have prefered to use something like this:
        String test = "SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'"+
                " category:MDC\_PULS\_OXIM\_SAT\_O2 OR category:MDC\_PULS\_OXIM\_PULS\_RATE AND date:[2016\-08\-11T16\:30\:09\+02\:00 TO 2016\-08\-11T16\:31\:28\+02\:00]')" +
                ""+"  LIMIT 50;";
ResultSet rt = session.execute(test);

But with above query, I'm getting 0 results, and I know there are entries in the database for effectiveDateTime in 'content' matching that "column" in the json.

Is that possible in the project's current implementation and the modification I made to the search index?

Examples of data contained in the database:
Row[Observation, Thu Aug 11 16:29:48 CEST 2016, test, {"resourceType":"Observation","category":[{"text":"MDC_PULS_OXIM_SAT_O2"}],"effectiveDateTime":"2016-08-11T16:29:48+02:00","valueQuantity":{"value":98.0}}, json, obs33, active, 1]
Row[Observation, Thu Aug 11 16:29:49 CEST 2016, test, {"resourceType":"Observation","category":[{"text":"MDC_PULS_OXIM_SAT_O2"}],"effectiveDateTime":"2016-08-11T16:29:49+02:00","valueQuantity":{"value":98.0}}, json, obs35, active, 1]

Once again, thanks for an interesting project!

kind regards, Martin Olsson

**Comment by jmiddleton** [comment] 2016-08-12 11:13
Hi Martin,

Thanks for the issue. Look I haven't done much more on the project but I will setup the environment and test the issue with dates. 

In the meantime, I would suggest you to have a look how Stratio handle dates as my implementation is based on their codebase (https://github.com/Stratio/cassandra-lucene-index).

Regards,
Jorge

**Comment by Tagertswe** [comment] 2016-08-12 12:28
Thank you for the quick response Jorge!
I will investigate Stratio.

kind regards,
Martin Olsson

**Comment by jmiddleton** [comment] 2016-08-14 15:45
Hi Martin, 

It seems what the index is storing for dates are not compatibles with the search. When the index is created date fields are converted and stored as Long. However the search using date:[date_1 TO date_2] is processed by Lucene as TermRangeFilter. That filter will search in lexicographically order so dates as numbers. In my local I have changed the code to store the date as string and the search now works as expected however I would like to test more scenarios. The problem is similar to the link below.

http://stackoverflow.com/questions/5495645/indexing-and-searching-date-in-lucene 

With this change the query parameter looks like: `date:[20150114140000000 TO 20160514140000000]'` which I don't like it so I will try to improve it.

Also, I found another issues with codes that have dash "-". In this case the default Lucene's analyzer understands dashes as a search by two values (value1-value2) instead of just one value. I have changed the default analyser to `WhitespaceAnalyzer` and now it's working.

Regards,
Jorge

**Comment by jmiddleton** [comment] 2016-08-14 16:51
Hi Martin,

I run some more tests and now it looks better. Please have a look and let me know. Now you should be able to execute the following queries:
- resource_type:Observation AND date:[20150514080518 TO 20150514080520] in case "effectiveDateTime" is something like "2015-05-14T18:05:19"
- resource_type:Observation AND date:[20150511 TO 20150513]
- or any combination up to seconds: yyyyMMddHHmmss

Let me know if you have issues. I think you will have to rebuild your indexes. As I believe you are testing, please delete and insert the records again.

Thanks,
Jorge

**Comment by Tagertswe** [comment] 2016-08-16 14:39
Hello Jorge!

I did a test with the feedback you wrote, but no success.

I did the following query:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND date:2016-08-16T16:23:47')  LIMIT 50;

as well as one without escaped date characters:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND date:20160816162347')  LIMIT 50;

I also tried with date ranges, but reverted back to a single date match.

The rows look like this:
Row[obs7, 1, Tue Aug 16 16:23:21 CEST 2016, test, {"resourceType":"Observation","category":[{"text":"MDC_TTHOR_RESP_RATE"}],"effectiveDateTime":"2016-08-16T16:23:21","valueQuantity":{"value":15.0}}, json, Observation, active]

Another note though, as I create observation objects for the incoming simulated medical data, I also noticed that setting effectiveDateTime in DSTU3 standard doesn't like if you remove the timezone offset, so I did that after constructing a json string in order to get the proper data inputed according to your instructions.

kind regards,
Martin

**Comment by jmiddleton** [comment] 2016-08-16 22:49
Hi Martin,

I think I forgot to push the image. Are you testing with my docker image or you have a copy of this repo?

I just pushed the image to docker hub so you can test it. Tonight I'm going to add your test case and see what happen.

Please note that the correct date format should be without dashes or colon, just numbers as per your second query.

Also, I changed the version of HAPI library to 1.5 just in case there are improvement.

Finally, I have created a cassandra-3.7 branch where I'm planning to upgrade the version of Cassandra 3.7 and HAPI 1.6. I'll let you know when it's ready.

Thanks,
Jorge

**Comment by Tagertswe** [comment] 2016-08-17 06:20
Hello Jorge!
Actually I compiled a .jar based on this repo (with mvn clean package) and put in the lib folder for cassandra for the changes that was made over the last weekend.

However I noticed  2 compiling errors with Hapi 1.5-Snapshot, and therefore had to change to Hapi 1.5. in the pom.xml in the root folder when cloning your repo.

The 2nd compiling error occurred in:
https://github.com/jmiddleton/cassandra-fhir-index/blob/a8a15a1d1b65c26dadf72dfb01a8bea5882a1727/fhir-index-plugin/src/main/java/io/puntanegra/fhir/index/search/extractor/TokenSearchParameterExtractor.java

In which I commented line 122.
But I see based on the latest commits that you noticed that already.

I will  try compile the project again based on your new changes as well as the docker and get back to you on my findings.

That's great news about a new Cassandra version, I look forward to testing it!

kind regards,
Martin

**Comment by jmiddleton** [comment] 2016-08-17 06:26
Thanks Martin,

You are welcome to update or add improvement to the source code 😊

Sorry if I don't reply on time but I can only work in my spare time.

Jorge

**Comment by Tagertswe** [comment] 2016-08-17 08:31
Hello Jorge,

Cool! I'll keep that in mind if I find any future improvements that work :) 

I tested with a new compile of your project with the following query:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,' date:20160817091728')  LIMIT 50;
as well as:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND date:20160817091728')  LIMIT 50;

But didn't get any matches.

Example of the row (one of many) in database that I'm looking for:
Row[obs10, 1, Wed Aug 17 09:17:28 CEST 2016, test, {"resourceType":"Observation","category":[{"text":"MDC_ECG_HEART_RATE"}],"effectiveDateTime":"2016-08-17T09:17:28","valueQuantity":{"value":60.0}}, json, Observation, active]

The results from using the docker approach:

Query:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND date:20160817095812')  LIMIT 50;

result: 0 matches.

example of row contained in database:
Row[obs0, 1, Wed Aug 17 09:58:12 CEST 2016, test, {"resourceType":"Observation","category":[{"text":"MDC_ECG_HEART_RATE"}],"effectiveDateTime":"2016-08-17T09:58:12","valueQuantity":{"value":60.0}}, json, Observation, active]

I'm also attaching build.gradle files from my java client that fetches the matching data from database, as well as build.gradle from my java "server" program that intercepts medical data from OpenICE and sends to database.

**# build.gradle java "server" program:**

`apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'eclipse'
//apply plugin: 'javafx.plugin'
// Declares binary plugin and its required JavaFX classpath
apply from: "http://dl.bintray.com/content/shemnon/javafx-gradle/8.1.1/javafx.plugin"

// builds a gradle wrapper
// http://www.gradle.org/docs/current/userguide/gradle_wrapper.html
task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

mainClassName = "com.circulate.CirculateICE"

jfxDeploy {
    verbose = true
}

javafx {
    appID 'com.circulate.CirculateICE'
    appName 'CirculateICE'
    mainClass 'com.circulate.CirculateICE'

```
profiles {
    macosx {
```

//          javaRuntime = '/usr/lib/jvm/java-8-openjdk-amd64/'

//          bundleArguments = [
                    // for mac apps
//                  'mac.CFBundleIdentifier' : 'org.mdpnp.apps.testapp.OpenICE',
//                  'mac.CFBundleName' : 'OpenICE',
//                  'mac.signing-key-user-name' : 'JEFFREY PLOURDE',
                    //'mac.signing-key-developer-id-app' : 'Developer ID Application: JEFFREY PLOURDE', // usually redundant with mac.signing-key-user-name
                    // for PKG bundles
                    //'mac.signing-key-developer-id-installer' : 'Developer ID Installer: JEFFREY PLOURDE', // usually redundant with mac.signing-key-user-name

```
                // for Mac App Store Ready bundles
                //'mac.app-store-entitlements' : 'src/deploy/package/NetworkEntitlements.entitlements',
                //'mac.signing-key-app' : '3rd Party Mac Developer Applicaiton: JEFFREY PLOURDE', // usually redundant with mac.signing-key-user-name
                //'mac.signing-key-pkg' : '3rd Party Mac Developer Installer: JEFFREY PLOURDE', // usually redundant with mac.signing-key-user-name
```

//          ]
        }
        windows {

```
    }
    linux {

    }
}
```

}

dependencies {
    compile 'org.mdpnp:x73-idl-rti-dds:0.6.3' //includes all the openIce components
    compile 'org.mdpnp:demo-devices:0.6.3'
    compile 'org.mdpnp:philips:0.6.3'
    compile 'org.mdpnp:philips:0.6.3'
    compile 'org.mdpnp:oridion:0.6.3'
    compile 'org.mdpnp:draeger:0.6.3'
    compile 'org.mdpnp:cpc:0.6.3'
    compile 'org.mdpnp:fluke:0.6.3'
    compile 'org.mdpnp:masimo:0.6.3'
    compile 'org.mdpnp:nellcor:0.6.3'
    compile 'org.mdpnp:puritanbennett:0.6.3'
    compile 'org.mdpnp:nonin:0.6.3'
    compile 'org.mdpnp:simulated:0.6.3'
//  compile 'org.mdpnp:ge:0.6.3'
    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.3.1'

```
//Added for Hl7 export functionality in this project
compile group: 'ca.uhn.hapi', name: 'hapi-base', version: '2.2'
compile group: 'ca.uhn.hapi', name: 'hapi-structures-v26', version: '2.2'
compile group: 'org.controlsfx', name: 'controlsfx', version: '8.20.9' , classifier: 'MDPNP0001'
compile group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-base', version: '1.5'
compile group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-structures-dstu2', version: '1.5'
compile group: 'commons-cli', name: 'commons-cli', version: '1.2'
```

// https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-structures-dstu3
    compile group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-structures-dstu3', version: '1.5'

```
// https://mvnrepository.com/artifact/org.apache.cassandra/cassandra-all
compile group: 'org.apache.cassandra', name: 'cassandra-all', version: '3.0.4'
// https://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-mapping
compile group: 'com.datastax.cassandra', name: 'cassandra-driver-mapping', version: '3.1.0'
// https://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-core
compile group: 'com.datastax.cassandra', name: 'cassandra-driver-core', version: '3.1.0'
```

// https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-validation-resources-dstu3
    compile group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-validation-resources-dstu3', version: '1.5'

```
compile 'com.fasterxml.jackson.core:jackson-core:2.7.3'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.7.3'
compile 'com.fasterxml.jackson.core:jackson-databind:2.7.3'
```

}

repositories {
  maven { url 'http://build.openice.info/artifactory/libs-snapshot' }
  maven { url 'http://build.openice.info/artifactory/libs-release' }
  mavenCentral()
}
`

# **build.gradle java client:**

`group '1'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.5

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'

```
compile 'com.fasterxml.jackson.core:jackson-core:2.7.3'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.7.3'
compile 'com.fasterxml.jackson.core:jackson-databind:2.7.3'
compile 'joda-time:joda-time:2.3'

compile group: 'org.apache.cassandra', name: 'cassandra-all', version: '3.0.4'


// https://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-mapping
compile group: 'com.datastax.cassandra', name: 'cassandra-driver-mapping', version: '3.1.0'
// https://mvnrepository.com/artifact/com.datastax.cassandra/cassandra-driver-core
compile group: 'com.datastax.cassandra', name: 'cassandra-driver-core', version: '3.1.0'
```

}
`

**Comment by jmiddleton** [comment] 2016-08-17 11:43
Hey Martin, can you validate the following?

I run a test with "effectiveDateTime": "2016-08-17T07:14:35" but Lucene got 20160816211435. The class `org.apache.lucene.documents.DateTools` converts dates using GMT as timezone. 

So, then I tried with "effectiveDateTime": "2016-08-17T07:14:35-10:00" (Australia timezone - AEST) but it didn't work, not sure why yet.

Finally I decided to change the implementation to use SimpleDateFormat and now I think it's working.

Also, try to configure Cassandra log level to log LuceneService like the below log. This will help you to debug how the index values are stored.

`20:54:50.831 [SharedPool-Worker-2] DEBUG i.p.fhir.index.lucene.LuceneService - Indexing Document<indexed,omitNorms,indexOptions=DOCS<date:20150817231728> indexed,omitNorms,indexOptions=DOCS<code_system:http://loinc.org> indexed,omitNorms,indexOptions=DOCS<code:12345-51> indexed,tokenized<resource_type:Observation> indexed,tokenized,omitNorms,indexOptions=DOCS,numericType=LONG,numericPrecisionStep=16,docValuesType=NUMERIC<_token:-690465374983050601> stored,indexed,omitNorms,indexOptions=DOCS,docValuesType=SORTED<_partition_key:[6f 62 73 5f 30]> stored,indexed,omitNorms,indexOptions=DOCS,docValuesType=SORTED<_primary_key:[0 8 f6 6a f9 66 52 6d aa 97 0 0 5 6f 62 73 5f 30 0 0 12 0 4 0 0 0 1 0 0 8 0 0 1 56 98 23 af c5 0 0]>> with term _primary_key:[0 8 f6 6a f9 66 52 6d aa 97 0 0 5 6f 62 73 5f 30 0 0 12 0 4 0 0 0 1 0 0 8 0 0 1 56 98 23 af c5 0 0] in idx_fir_resources`

Download the latest version and let me know.

thanks,
Jorge

**Comment by Tagertswe** [comment] 2016-08-17 12:26
Hello Jorge,

I'm happy to report that your latest fix worked!

I performed a simple query first, and then this advanced one:
SELECT \* FROM test.FHIR_RESOURCES WHERE expr(idx_fhir_resources,'resource_type:Observation AND ( category:MDC_PULS_OXIM_PULS_RATE OR category:MDC_PULS_OXIM_SAT_O2 ) AND date:[20160817140936 TO 20160817140937]')  LIMIT 50;

And it gave me 4 matches just as I expected  !

Thanks for the tips with setting the cassandra log level, I will have a look at that.

kind regards,
Martin

**Comment by jmiddleton** [comment] 2016-08-17 12:49
Hi Martin,

Nice to hear that. 

Yes, Cassandra server log, the logs is debug.log however not sure where to configure it.

Let me know if you need something else.

BTW, are you planing to use it in a project or it is just for learning purposes?

Cheers,
Jorge

**Comment by Tagertswe** [comment] 2016-08-17 14:34
Hello Jorge,

Right now it's just for research and development and currently in evaluation stage to know what underlying technologies we need to use in a current project, and if it could be useful.

Do you have any tips regarding the legal part if we were to use your project in the far future?

Cool, I'll keep it in mind if I come across any other bugs or thoughts that I may have  ! :)

kind regards,
Martin

**Comment by jmiddleton** [comment] 2016-08-18 08:48
It shouldn't be a problem the legal part. I haven't configured the license but if you needed we can do it.

I'm going to close the issue for now.

Regards,
Jorge

**Closed as completed by jmiddleton** 2016-08-18 08:48 UTC
